services:
  mysql:
    image: mysql:8.0.36
    container_name: auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--default-authentication-plugin=caching_sha2_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
      ]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: