spring:
  application:
    name: auth-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  jwt:
    secret: change-me
    expiration: 3600000
