spring:
  application:
    name: auth-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  jwt:
    secret: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDbGluaWMiLCJzdWIiOiJsdWlzbXpmIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTczNDExMTcwOCwiZXhwIjoxNzM0MTI2MTA4fQ.oAzRuaowrvoMCGM06s9LIgLtxVg1Bvuu1RE8b6AyDD4
    expiration: 3600000
